// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=agent
//

// Package agent is a generated GoMock package.
package agent

import (
	reflect "reflect"

	resty "github.com/go-resty/resty/v2"
	models "github.com/volchkovski/go-practicum-metrics/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// R mocks base method.
func (m *MockHTTPClient) R() *resty.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "R")
	ret0, _ := ret[0].(*resty.Request)
	return ret0
}

// R indicates an expected call of R.
func (mr *MockHTTPClientMockRecorder) R() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "R", reflect.TypeOf((*MockHTTPClient)(nil).R))
}

// SetTimeout mocks base method.
func (m *MockHTTPClient) SetTimeout(timeout any) *resty.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTimeout", timeout)
	ret0, _ := ret[0].(*resty.Client)
	return ret0
}

// SetTimeout indicates an expected call of SetTimeout.
func (mr *MockHTTPClientMockRecorder) SetTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeout", reflect.TypeOf((*MockHTTPClient)(nil).SetTimeout), timeout)
}

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// CollectExtraMetrics mocks base method.
func (m *MockMetricsCollector) CollectExtraMetrics() (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectExtraMetrics")
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectExtraMetrics indicates an expected call of CollectExtraMetrics.
func (mr *MockMetricsCollectorMockRecorder) CollectExtraMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectExtraMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectExtraMetrics))
}

// CollectRuntimeMetrics mocks base method.
func (m *MockMetricsCollector) CollectRuntimeMetrics() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectRuntimeMetrics")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// CollectRuntimeMetrics indicates an expected call of CollectRuntimeMetrics.
func (mr *MockMetricsCollectorMockRecorder) CollectRuntimeMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectRuntimeMetrics", reflect.TypeOf((*MockMetricsCollector)(nil).CollectRuntimeMetrics))
}

// MockStorageInterface is a mock of StorageInterface interface.
type MockStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockStorageInterfaceMockRecorder is the mock recorder for MockStorageInterface.
type MockStorageInterfaceMockRecorder struct {
	mock *MockStorageInterface
}

// NewMockStorageInterface creates a new mock instance.
func NewMockStorageInterface(ctrl *gomock.Controller) *MockStorageInterface {
	mock := &MockStorageInterface{ctrl: ctrl}
	mock.recorder = &MockStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageInterface) EXPECT() *MockStorageInterfaceMockRecorder {
	return m.recorder
}

// ReadMetrics mocks base method.
func (m *MockStorageInterface) ReadMetrics() []*models.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMetrics")
	ret0, _ := ret[0].([]*models.Metrics)
	return ret0
}

// ReadMetrics indicates an expected call of ReadMetrics.
func (mr *MockStorageInterfaceMockRecorder) ReadMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMetrics", reflect.TypeOf((*MockStorageInterface)(nil).ReadMetrics))
}

// ReplaceMetrics mocks base method.
func (m *MockStorageInterface) ReplaceMetrics(metrics ...*models.Metrics) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range metrics {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ReplaceMetrics", varargs...)
}

// ReplaceMetrics indicates an expected call of ReplaceMetrics.
func (mr *MockStorageInterfaceMockRecorder) ReplaceMetrics(metrics ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMetrics", reflect.TypeOf((*MockStorageInterface)(nil).ReplaceMetrics), metrics...)
}
